package config

import (
	"crypto/rand"
	"encoding/base64"
	"errors"
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"golang.org/x/crypto/bcrypt"
)

// BootstrapResult describes a first-run initialization. Password is only
// populated when a new credential was created; callers must not print it on
// subsequent idempotent runs.
type BootstrapResult struct {
	ConfigPath string
	EnvPath    string
	Username   string
	Password   string
	Created    bool
}

// Bootstrap creates a minimal Compose-ready config and a gitignored env file.
// Existing credentials are never replaced unless rotate is explicitly true.
func Bootstrap(dir string, rotate bool) (BootstrapResult, error) {
	if dir == "" {
		return BootstrapResult{}, errors.New("bootstrap directory must not be empty")
	}
	if err := os.MkdirAll(dir, 0o700); err != nil {
		return BootstrapResult{}, fmt.Errorf("create bootstrap directory: %w", err)
	}
	configPath := filepath.Join(dir, "config.yml")
	envPath := filepath.Join(dir, ".env")
	configExists := fileExists(configPath)
	envExists := fileExists(envPath)
	if !rotate && (configExists || envExists) {
		return BootstrapResult{ConfigPath: configPath, EnvPath: envPath, Username: "admin", Created: false}, nil
	}

	password, err := randomPassword()
	if err != nil {
		return BootstrapResult{}, err
	}
	hash, err := bcrypt.GenerateFromPassword([]byte(password), bcrypt.DefaultCost)
	if err != nil {
		return BootstrapResult{}, fmt.Errorf("hash bootstrap password: %w", err)
	}

	cfg := defaults()
	cfg.Auth.Username = "admin"
	cfg.Auth.PasswordHash = string(hash)
	cfg.RTorrent.SCGI = "tcp://rtorrent:5000"
	cfg.Directories.Default = "/downloads"
	cfg.Directories.Watch = "/watch"
	cfg.Directories.Session = "/session"
	cfg.Volumes = []string{"/downloads"}
	if err := Save(configPath, cfg); err != nil {
		return BootstrapResult{}, err
	}
	// Compose interpolates dollar signs in env files. Escape bcrypt's `$`
	// delimiters so the container receives the original hash literally.
	composeHash := strings.ReplaceAll(string(hash), "$", "$$")
	env := fmt.Sprintf("# Generated by blackbird --bootstrap; keep this file private.\nBLACKBIRD_PASSWORD_HASH=%s\n", composeHash)
	if err := os.WriteFile(envPath, []byte(env), 0o600); err != nil {
		return BootstrapResult{}, fmt.Errorf("write bootstrap env: %w", err)
	}
	return BootstrapResult{ConfigPath: configPath, EnvPath: envPath, Username: "admin", Password: password, Created: true}, nil
}

func fileExists(path string) bool {
	_, err := os.Stat(path)
	return err == nil
}

func randomPassword() (string, error) {
	b := make([]byte, 24)
	if _, err := rand.Read(b); err != nil {
		return "", fmt.Errorf("generate bootstrap password: %w", err)
	}
	return base64.RawURLEncoding.EncodeToString(b), nil
}
