import { For, Show, createEffect, createMemo, createSignal, onCleanup, onMount } from "solid-js";
import { closeMove, moveHashes, moveOpen, showToast } from "../store/ui";
import { torrentList } from "../store/session";

type Mode = "move_files" | "set_directory";
type Browser = { roots: string[]; path: string; parent?: string; entries: Array<{ name: string; path: string }> };
type Job = { id: string; status: "running" | "completed" | "cancelled"; results: Array<{ hash: string; status: string; error?: string }> };
const RECENT_KEY = "blackbird.move-recent.v1";
function recent() { try { return JSON.parse(localStorage.getItem(RECENT_KEY) ?? "[]") as string[]; } catch { return []; } }
function remember(path: string) { localStorage.setItem(RECENT_KEY, JSON.stringify([path, ...recent().filter((item) => item !== path)].slice(0, 6))); }

export function MoveDataModal() {
  const [mode, setMode] = createSignal<Mode>("move_files"); const [browser, setBrowser] = createSignal<Browser | null>(null); const [destination, setDestination] = createSignal(""); const [job, setJob] = createSignal<Job | null>(null);
  const [perLabelDestinations, setPerLabelDestinations] = createSignal<Record<string, string>>({});
  const selected = createMemo(() => torrentList().filter((torrent) => moveHashes().includes(torrent.hash)));
  let timer: number | undefined;
  const browse = async (path = "") => { try { const response = await fetch(`/api/directories${path ? `?path=${encodeURIComponent(path)}` : ""}`); if (!response.ok) throw new Error("Could not browse that directory"); const data = await response.json() as Browser; setBrowser(data); if (!destination()) setDestination(data.path); } catch (error) { showToast(error instanceof Error ? error.message : "Could not browse directories"); } };
  createEffect(() => { if (moveOpen()) { setJob(null); setDestination(""); setMode("move_files"); void browse(); void fetch("/api/settings").then((response) => response.ok ? response.json() as Promise<{ directories?: { per_label?: Record<string, string> } }> : null).then((settings) => setPerLabelDestinations(settings?.directories?.per_label ?? {})).catch(() => {}); } });
  onMount(() => { const key = (event: KeyboardEvent) => { if (event.key === "Escape" && moveOpen() && !job()) closeMove(); }; document.addEventListener("keydown", key); onCleanup(() => { document.removeEventListener("keydown", key); if (timer) window.clearInterval(timer); }); });
  const poll = (id: string) => { if (timer) window.clearInterval(timer); timer = window.setInterval(() => void fetch(`/api/torrents/move/${encodeURIComponent(id)}`).then((response) => response.ok ? response.json() as Promise<Job> : Promise.reject()).then((next) => { setJob(next); if (next.status !== "running" && timer) window.clearInterval(timer); }).catch(() => {}), 400); };
  const start = async () => { if (!destination() || job()) return; try { const response = await fetch("/api/torrents/move", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ hashes: moveHashes(), destination: destination(), mode: mode() }) }); const data = await response.json().catch(() => ({})) as Job & { error?: { message?: string } }; if (!response.ok) throw new Error(data.error?.message || "Could not start move"); remember(destination()); setJob(data); poll(data.id); } catch (error) { showToast(error instanceof Error ? error.message : "Could not start move"); } };
  const cancel = async () => { const active = job(); if (active) await fetch(`/api/torrents/move/${encodeURIComponent(active.id)}/cancel`, { method: "POST" }); };
  return <Show when={moveOpen()}><div class="modal-backdrop" role="presentation"><section class="move-modal" role="dialog" aria-modal="true" aria-label="Move torrent data"><header class="modal-title"><h2>Move torrent data</h2><button type="button" disabled={Boolean(job()?.status === "running")} onClick={closeMove}>✕</button></header><div class="add-body"><p class="move-notice"><Show when={selected().some((torrent) => torrent.state !== "stopped")}>Running torrents will be stopped, updated, and restarted automatically. </Show>{mode() === "move_files" ? "Files are moved with copy-and-verify fallback across filesystems." : "Use this only after data has already been relocated."}</p><div class="add-segments"><button classList={{ active: mode() === "move_files" }} type="button" disabled={Boolean(job())} onClick={() => setMode("move_files")}>Move files</button><button classList={{ active: mode() === "set_directory" }} type="button" disabled={Boolean(job())} onClick={() => setMode("set_directory")}>Set directory only</button></div><div class="move-shortcuts"><span>Configured roots, label destinations, and recent destinations</span><For each={[...(browser()?.roots ?? []), ...Object.values(perLabelDestinations()), ...recent()]}>{(path) => <button type="button" disabled={Boolean(job())} onClick={() => { setDestination(path); void browse(path); }}>{path}</button>}</For></div><div class="directory-browser"><div><button type="button" disabled={!browser()?.parent || Boolean(job())} onClick={() => void browse(browser()!.parent)}>↑</button><b>{browser()?.path || "Loading…"}</b><button type="button" disabled={Boolean(job())} onClick={() => browser() && setDestination(browser()!.path)}>Use this folder</button></div><For each={browser()?.entries ?? []}>{(entry) => <button type="button" disabled={Boolean(job())} onClick={() => void browse(entry.path)}>📁 {entry.name}</button>}</For></div><Show when={job()}>{(active) => <div class="add-results"><For each={active().results}>{(result) => <div classList={{ success: result.status === "completed", failure: result.status === "failed" }}><span>{result.hash}</span><b>{result.error || result.status}</b></div>}</For></div>}</Show></div><footer class="modal-footer"><Show when={job()?.status === "running"} fallback={<><button class="modal-cancel" type="button" onClick={closeMove}>{job() ? "Close" : "Cancel"}</button><button class="modal-submit" type="button" disabled={!destination()} onClick={() => void start()}>Continue</button></>}><button class="modal-cancel" type="button" onClick={() => void cancel()}>Cancel move</button></Show></footer></section></div></Show>;
}
